name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'release'}

    env:
      export DISPLAY=localhost:0.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install X11 dependencies
      if runner.os == 'macOS'
      run: |
        brew install xquartz --cask

    - name: Run tests
      run: sbt test
    - name: Run gui
      run: sbt "runMain dailyLearn.gui.view"
